#!/bin/bash -eux
source "$(dirname $0)/bin/conf"
[ "$USER" = "root" ]

# logディレクトリ作成       /var/log/bashproc_contents
# timestampディレクトリ作成 /var/www/bashproc_contents_data
mkdir -p "${log_dir}" "${data_dir}" "${data_dir}/counters"
chown www-data:www-data "${log_dir}" "${data_dir}" "{data_dir}/counters"

# INSTALL THIS SYSTEM
rsync -av --delete "$(dirname $0)/bin/" "${app_dir/}"
chown www-data:www-data "${app_dir}" -R

# RENAME FETCH CGI
cd "${app_dir}"
rnd=$(cat /dev/urandom | tr -cd 0-9a-zA-Z | head -c 32)
# /home/yano/rnd が存在する場合、それをrnd に代入する（最初に生成したものを使い回す）意図
[ -e "/home/yano/rnd" ] && rnd=$(cat /home/yano/rnd ) # REMOVE ON RELEASE

mv "fetch" "fetch_${rnd}.cgi"


# 記事リポジトリを削除し、git cloneする
rm -rf "${contents_dir:?}"
cd "${www_dir}"
git clone "https://github.com/${contents_owner}/${contents}"
chown www-data:www-data "${contents_dir}" -R

echo "call fetch_${rnd}.cgi from GitHub"

